bs_online_sales_data_columns = [
    'order_number', 'order_type', 'platform', 'split_order_platform_number',
    'platform_order_number', 'company_name', 'order_status', 'payment_status',
    'payment_method', 'payment_number', 'material_code', 'product_name',
    'product_category', 'product_brand', 'product_model', 'color', 'system_form',
    'original_price', 'sale_price', 'quantity', 'serial_code', 'store_discount',
    'platform_discount', 'gift_discount', 'other_discount', 'total_discount',
    'two_invoice_amount', 'invoice_amount', 'scm_price', 'province', 'city',
    'district', 'delivery_address', 'recipient', 'recipient_phone',
    'delivery_warehouse', 'delivery_status', 'tracking_number', 'logistics_company',
    'is_invoice', 'invoice_title', 'invoice_number', 'invoice_request_details',
    'order_remarks', 'is_presale_order', 'order_deposit', 'deposit_payment_time',
    'orderer', 'orderer_phone', 'order_time', 'order_payment_time',
    'order_reception_time', 'reviewer', 'review_time', 'last_modifier',
    'last_modification_time', 'shipment_time', 'receipt_time', 'is_offline_shipment',
    'is_after_sales', 'after_sales_time', 'posting_status', 'user_message',
    'seller_remarks', 'total_invoice_amount', 'contract_platform', 'contract_phone',
    'order_source', 'store_level', 'province_affiliation', 'is_split_order',
    'is_main_order', 'is_reorder'
]
