[{'systemCode': 'iot', 'deviceAddr': 10023646, 'deviceName': '可靠性实验室-1', 'lat': 0.0, 'lng': 0.0,
  'deviceStatus': 'normal',
  'relayStatus': '[{"relayNo":1,"relayStatus":0},{"relayNo":2,"relayStatus":0},{"relayNo":3,"relayStatus":0},{"relayNo":4,"relayStatus":0},{"relayNo":5,"relayStatus":0},{"relayNo":6,"relayStatus":0},{"relayNo":7,"relayStatus":0},{"relayNo":8,"relayStatus":0},{"relayNo":9,"relayStatus":0},{"relayNo":10,"relayStatus":0},{"relayNo":11,"relayStatus":0},{"relayNo":12,"relayStatus":0},{"relayNo":13,"relayStatus":0},{"relayNo":14,"relayStatus":0},{"relayNo":15,"relayStatus":0},{"relayNo":16,"relayStatus":0}]',
  'relayStatusItems': [{'relayNo': 1, 'relayStatus': 0}, {'relayNo': 2, 'relayStatus': 0},
                       {'relayNo': 3, 'relayStatus': 0}, {'relayNo': 4, 'relayStatus': 0},
                       {'relayNo': 5, 'relayStatus': 0}, {'relayNo': 6, 'relayStatus': 0},
                       {'relayNo': 7, 'relayStatus': 0}, {'relayNo': 8, 'relayStatus': 0},
                       {'relayNo': 9, 'relayStatus': 0}, {'relayNo': 10, 'relayStatus': 0},
                       {'relayNo': 11, 'relayStatus': 0}, {'relayNo': 12, 'relayStatus': 0},
                       {'relayNo': 13, 'relayStatus': 0}, {'relayNo': 14, 'relayStatus': 0},
                       {'relayNo': 15, 'relayStatus': 0}, {'relayNo': 16, 'relayStatus': 0}], 'dataItem': [{'nodeId': 1,
                                                                                                            'registerItem': [
                                                                                                                {
                                                                                                                    'registerId': 1,
                                                                                                                    'data': '19.4',
                                                                                                                    'value': 19.399999618530273,
                                                                                                                    'alarmLevel': 0,
                                                                                                                    'alarmColor': 'ff0000',
                                                                                                                    'alarmInfo': '',
                                                                                                                    'unit': '℃',
                                                                                                                    'registerName': '温度'},
                                                                                                                {
                                                                                                                    'registerId': 2,
                                                                                                                    'data': '78.7',
                                                                                                                    'value': 78.70000457763672,
                                                                                                                    'alarmLevel': 0,
                                                                                                                    'alarmColor': 'ff0000',
                                                                                                                    'alarmInfo': '',
                                                                                                                    'unit': '%',
                                                                                                                    'registerName': '湿度'}]}],
  'timeStamp': 1726034551819}]
